import type { Config } from "tailwindcss";

// Design tokens preserved verbatim from the Stitch export (DESIGN.md + code.html files).
const config: Config = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-container-low": "#f6f3f5",
        "inverse-on-surface": "#f3f0f2",
        "on-error-container": "#93000a",
        outline: "#76777d",
        "secondary-fixed-dim": "#ffb3ad",
        "surface-dim": "#dcd9db",
        "outline-variant": "#c6c6cd",
        "on-secondary-fixed-variant": "#930013",
        "secondary-fixed": "#ffdad7",
        primary: "#0F172A",
        "on-primary-fixed": "#131b2e",
        surface: "#fcf8fa",
        "on-tertiary-fixed-variant": "#574425",
        "on-error": "#ffffff",
        secondary: "#b61722",
        "on-primary-fixed-variant": "#3f465c",
        "surface-bright": "#fcf8fa",
        "surface-container-lowest": "#ffffff",
        "on-tertiary-container": "#98805d",
        "primary-fixed-dim": "#bec6e0",
        error: "#ba1a1a",
        "growth-green": "#10B981",
        "on-tertiary-fixed": "#271901",
        "border-subtle": "#E2E8F0",
        "error-container": "#ffdad6",
        "surface-muted": "#F8FAFC",
        "on-tertiary": "#ffffff",
        "secondary-container": "#da3437",
        "on-secondary-fixed": "#410004",
        "on-primary-container": "#7c839b",
        "tertiary-container": "#271901",
        "on-surface": "#1b1b1d",
        background: "#fcf8fa",
        "surface-variant": "#e4e2e4",
        "on-surface-variant": "#45464d",
        "tertiary-fixed": "#fcdeb5",
        "warning-amber": "#F59E0B",
        "surface-container": "#f0edef",
        "surface-container-highest": "#e4e2e4",
        "on-primary": "#ffffff",
        "primary-container": "#131b2e",
        "on-secondary-container": "#fffbff",
        "reasoning-blue": "#3B82F6",
        "on-secondary": "#ffffff",
        tertiary: "#000000",
        "tertiary-fixed-dim": "#dec29a",
        "on-background": "#1b1b1d",
        "inverse-primary": "#bec6e0",
        "surface-tint": "#565e74",
        "inverse-surface": "#303032",
        "primary-fixed": "#dae2fd",
        "surface-container-high": "#eae7e9",
        "accent-red": "#EF4444",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        gutter: "1.5rem",
        "stack-compact": "0.5rem",
        "stack-default": "1rem",
        "margin-mobile": "1rem",
        "container-max": "1440px",
        "section-gap": "2rem",
        sidebar: "240px",
      },
      fontFamily: {
        "body-base": ["Inter", "sans-serif"],
        "metric-display": ["Inter", "sans-serif"],
        "label-bold": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "data-mono": ["Inter", "monospace"],
      },
      fontSize: {
        "body-base": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "metric-display": [
          "32px",
          { lineHeight: "40px", letterSpacing: "0", fontWeight: "600" },
        ],
        "metric-display-sm": [
          "24px",
          { lineHeight: "32px", letterSpacing: "0", fontWeight: "600" },
        ],
        "label-bold": [
          "12px",
          { lineHeight: "16px", letterSpacing: "0.01em", fontWeight: "600" },
        ],
        "body-sm": ["13px", { lineHeight: "18px", fontWeight: "400" }],
        "headline-md": ["18px", { lineHeight: "28px", fontWeight: "600" }],
        "headline-lg": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "data-mono": ["13px", { lineHeight: "18px", fontWeight: "500" }],
      },
      boxShadow: {
        glass: "0 14px 40px rgba(15, 23, 42, 0.08)",
      },
      backdropBlur: {
        glass: "16px",
      },
    },
  },
  plugins: [],
};
export default config;
