export const routes = {
  onboarding: "/onboarding",
  overview: "/overview",
  opportunities: "/opportunities",
  opportunity: (id: string) => `/opportunities/${id}`,
  experiments: "/experiments",
  experiment: (id: string) => `/experiments/${id}`,
  aiCommerce: "/ai-commerce",
  aiBuyer: "/ai-buyer",
  aiBuyerBasket: "/ai-buyer/basket",
  checkout: (orderIntentId: string) => `/checkout/${orderIntentId}`,
  paymentSuccess: "/payment/success",
  paymentFailure: "/payment/failure",
  products: "/products",
  orders: "/orders",
  payments: "/payments",
  agents: "/agents",
  policies: "/policies",
  audit: "/audit",
  auditDetail: (id: string) => `/audit/${id}`,
};

export const sidebarNav = [
  { label: "Overview", href: routes.overview, icon: "layout-dashboard" as const },
  { label: "Opportunities", href: routes.opportunities, icon: "target" as const },
  { label: "Experiments", href: routes.experiments, icon: "flask-conical" as const },
  { label: "AI Commerce", href: routes.aiCommerce, icon: "sparkles" as const },
  { label: "Orders", href: routes.orders, icon: "shopping-cart" as const },
  { label: "Products", href: routes.products, icon: "package" as const },
  { label: "Payments", href: routes.payments, icon: "credit-card" as const },
  { label: "Agent Activity", href: routes.agents, icon: "bot" as const },
  { label: "Policies", href: routes.policies, icon: "shield-check" as const },
  { label: "Audit Trail", href: routes.audit, icon: "file-search" as const },
];
